alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias grep='grep --color=auto'
alias h='history'
alias l='ls -CF'
alias la='ls -la'
alias ll='ls -l'
alias ls='ls --color=auto'
alias rm='rm -i'
